server:
  port: 7001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.crudapi.bean